"""add slug to category

Revision ID: 05cd7812adfe
Revises: fd50d41bfdde
Create Date: 2025-12-13 11:42:40.430884

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '05cd7812adfe'
down_revision: Union[str, Sequence[str], None] = 'fd50d41bfdde'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('customer_name', sa.String(), nullable=False),
    sa.Column('customer_phone', sa.String(), nullable=False),
    sa.Column('customer_email', sa.String(), nullable=True),
    sa.Column('customer_address', sa.String(), nullable=False),
    sa.Column('payment_status', sa.String(), nullable=True),
    sa.Column('order_status', sa.String(), nullable=True),
    sa.Column('total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('NOW()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('categories', sa.Column('description', sa.String(), nullable=True))
    op.drop_constraint(op.f('categories_slug_key'), 'categories', type_='unique')
    op.create_index(op.f('ix_categories_slug'), 'categories', ['slug'], unique=True)
    op.drop_column('categories', 'created_at')
    op.add_column('product_images', sa.Column('image_url', sa.String(), nullable=False))
    op.create_index(op.f('ix_product_images_id'), 'product_images', ['id'], unique=False)
    op.drop_constraint(op.f('product_images_product_id_fkey'), 'product_images', type_='foreignkey')
    op.create_foreign_key(None, 'product_images', 'products', ['product_id'], ['id'])
    op.drop_column('product_images', 'url')
    op.drop_column('product_images', 'is_main')
    op.alter_column('products', 'description',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('products', 'price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Float(),
               existing_nullable=False)
    op.drop_constraint(op.f('products_slug_key'), 'products', type_='unique')
    op.drop_constraint(op.f('products_category_id_fkey'), 'products', type_='foreignkey')
    op.create_foreign_key(None, 'products', 'categories', ['category_id'], ['id'])
    op.drop_column('products', 'is_active')
    op.drop_column('products', 'slug')
    op.drop_column('products', 'updated_at')
    op.drop_column('products', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('slug', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('products', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.create_foreign_key(op.f('products_category_id_fkey'), 'products', 'categories', ['category_id'], ['id'], ondelete='SET NULL')
    op.create_unique_constraint(op.f('products_slug_key'), 'products', ['slug'], postgresql_nulls_not_distinct=False)
    op.alter_column('products', 'price',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=False)
    op.alter_column('products', 'description',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.add_column('product_images', sa.Column('is_main', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('product_images', sa.Column('url', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'product_images', type_='foreignkey')
    op.create_foreign_key(op.f('product_images_product_id_fkey'), 'product_images', 'products', ['product_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_product_images_id'), table_name='product_images')
    op.drop_column('product_images', 'image_url')
    op.add_column('categories', sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_categories_slug'), table_name='categories')
    op.create_unique_constraint(op.f('categories_slug_key'), 'categories', ['slug'], postgresql_nulls_not_distinct=False)
    op.drop_column('categories', 'description')
    op.drop_table('order_items')
    op.drop_table('orders')
    # ### end Alembic commands ###
